const std = @import("std");
const arch = @import("../main.zig");
const krn = @import("kernel");
const errors = krn.errors;

pub const SyscallHandler = fn (
    a1: u32,
    a2: u32,
    a3: u32,
    a4: u32,
    a5: u32,
    a6: u32,
) errors.PosixError!u32;

fn notImpl(_: u32, _: u32, _: u32, _: u32, _: u32, _: u32) !u32 {
    const state: *arch.Regs = @ptrFromInt(arch.gdt.tss.esp0 - @sizeOf(arch.Regs));
    krn.logger.WARN("syscall {d} {s} is not implemented", .{
        state.eax,
        @tagName(@as(Syscall, @enumFromInt(state.eax)))
    });
    return errors.PosixError.EINVAL;
}

pub const SyscallTable = brk: {
    @setEvalBranchQuota(1700);
    break :brk std.EnumMap(Syscall, *const SyscallHandler).init(.{
        .SYS_setup                      = &notImpl,
        .SYS_exit                       = @ptrCast(&krn.syscalls.exit.exit),
        .SYS_fork                       = @ptrCast(&krn.syscalls.fork.fork),
        .SYS_read                       = @ptrCast(&krn.syscalls.read.read),
        .SYS_write                      = @ptrCast(&krn.syscalls.write.write),
        .SYS_open                       = @ptrCast(&krn.syscalls.open.open),
        .SYS_close                      = @ptrCast(&krn.syscalls.close.close),
        .SYS_waitpid                    = &notImpl,
        .SYS_creat                      = &notImpl,
        .SYS_link                       = @ptrCast(&krn.syscalls.link.link),
        .SYS_unlink                     = @ptrCast(&krn.syscalls.unlink.unlink),
        .SYS_execve                     = @ptrCast(&krn.syscalls.exec.execve),
        .SYS_chdir                      = @ptrCast(&krn.syscalls.chdir.chdir),
        .SYS_time                       = @ptrCast(&krn.syscalls.time.time),
        .SYS_mknod                      = @ptrCast(&krn.syscalls.mknod.mknod),
        .SYS_chmod                      = @ptrCast(&krn.syscalls.chmod.chmod),
        .SYS_lchown                     = @ptrCast(&krn.syscalls.chown.lchown),
        .SYS_break                      = &notImpl,
        .SYS_oldstat                    = &notImpl,
        .SYS_lseek                      = @ptrCast(&krn.syscalls.lseek.lseek),
        .SYS_getpid                     = @ptrCast(&krn.syscalls.id.getPID),
        .SYS_mount                      = @ptrCast(&krn.syscalls.mount.mount),
        .SYS_umount                     = @ptrCast(&krn.syscalls.mount.umount),
        .SYS_setuid                     = @ptrCast(&krn.syscalls.id.setUID),
        .SYS_getuid                     = @ptrCast(&krn.syscalls.id.getUID),
        .SYS_stime                      = &notImpl,
        .SYS_ptrace                     = &notImpl,
        .SYS_alarm                      = &notImpl,
        .SYS_oldfstat                   = &notImpl,
        .SYS_pause                      = &notImpl,
        .SYS_utime                      = &notImpl,
        // .SYS_utimensat                  = @ptrCast(&krn.syscalls.time),
        .SYS_stty                       = &notImpl,
        .SYS_gtty                       = &notImpl,
        .SYS_access                     = @ptrCast(&krn.syscalls.access.access),
        .SYS_nice                       = &notImpl,
        .SYS_ftime                      = &notImpl,
        .SYS_sync                       = &notImpl,
        .SYS_kill                       = @ptrCast(&krn.syscalls.kill.kill),
        .SYS_rename                     = @ptrCast(&krn.syscalls.rename.rename),
        .SYS_renameat                   = @ptrCast(&krn.syscalls.rename.renameat),
        .SYS_renameat2                  = @ptrCast(&krn.syscalls.rename.renameat2),
        .SYS_mkdir                      = @ptrCast(&krn.syscalls.mkdir.mkdir),
        .SYS_rmdir                      = @ptrCast(&krn.syscalls.mkdir.rmdir),
        .SYS_dup                        = @ptrCast(&krn.syscalls.dup.dup),
        .SYS_pipe                       = @ptrCast(&krn.syscalls.pipe.pipe),
        .SYS_pipe2                      = @ptrCast(&krn.syscalls.pipe.pipe2),
        .SYS_times                      = &notImpl,
        .SYS_prof                       = &notImpl,
        .SYS_brk                        = @ptrCast(&krn.syscalls.brk.brk),
        .SYS_setgid                     = @ptrCast(&krn.syscalls.id.setGID),
        .SYS_getgid                     = @ptrCast(&krn.syscalls.id.getPID),
        .SYS_signal                     = &notImpl,
        .SYS_geteuid                    = @ptrCast(&krn.syscalls.id.getEUID),
        .SYS_geteuid32                  = @ptrCast(&krn.syscalls.id.getEUID32),
        .SYS_getegid                    = @ptrCast(&krn.syscalls.id.getEGID),
        .SYS_acct                       = &notImpl,
        .SYS_umount2                    = @ptrCast(&krn.syscalls.mount.umount2),
        .SYS_lock                       = &notImpl,
        .SYS_ioctl                      = @ptrCast(&krn.syscalls.ioctl.ioctl),
        .SYS_fcntl                      = @ptrCast(&krn.syscalls.fcntl.fcntl),
        .SYS_fcntl64                    = @ptrCast(&krn.syscalls.fcntl.fcntl64),
        .SYS_mpx                        = &notImpl,
        .SYS_setpgid                    = @ptrCast(&krn.syscalls.id.setPGID),
        .SYS_ulimit                     = &notImpl,
        .SYS_oldolduname                = &notImpl,
        .SYS_umask                      = @ptrCast(&krn.syscalls.umask.umask),
        .SYS_chroot                     = &notImpl,
        .SYS_ustat                      = &notImpl,
        .SYS_dup2                       = @ptrCast(&krn.syscalls.dup.dup2),
        .SYS_getppid                    = @ptrCast(&krn.syscalls.id.getPPID),
        .SYS_getpgrp                    = &notImpl,
        .SYS_setsid                     = &notImpl,
        .SYS_sigaction                  = @ptrCast(&krn.syscalls.sigaction.sigaction),
        .SYS_sgetmask                   = &notImpl,
        .SYS_ssetmask                   = &notImpl,
        .SYS_setreuid                   = &notImpl,
        .SYS_setregid                   = &notImpl,
        .SYS_sigsuspend                 = &notImpl,
        .SYS_sigpending                 = @ptrCast(&krn.syscalls.sigaction.sigpending),
        .SYS_sethostname                = &notImpl,
        .SYS_setrlimit                  = &notImpl,
        .SYS_getrlimit                  = &notImpl,
        .SYS_getrusage                  = &notImpl,
        .SYS_gettimeofday               = &notImpl,
        .SYS_settimeofday               = &notImpl,
        .SYS_getgroups                  = &notImpl,
        .SYS_setgroups                  = &notImpl,
        .SYS_select                     = &notImpl,
        .SYS_symlink                    = @ptrCast(&krn.syscalls.symlink.symlink),
        .SYS_oldlstat                   = &notImpl,
        .SYS_readlink                   = @ptrCast(&krn.syscalls.readlink.readlink),
        .SYS_uselib                     = &notImpl,
        .SYS_swapon                     = &notImpl,
        .SYS_reboot                     = &notImpl,
        .SYS_readdir                    = &notImpl,
        .SYS_mmap                       = @ptrCast(&krn.syscalls.mmap.mmap),
        .SYS_munmap                     = @ptrCast(&krn.syscalls.mmap.munmap),
        .SYS_truncate                   = &notImpl,
        .SYS_ftruncate                  = &notImpl,
        .SYS_ftruncate64                = @ptrCast(&krn.syscalls.truncate.ftruncate64),
        .SYS_fchmod                     = &notImpl,
        .SYS_fchown                     = &notImpl,
        .SYS_fchownat                    = @ptrCast(&krn.syscalls.chown.fchownat),
        .SYS_getpriority                = &notImpl,
        .SYS_setpriority                = &notImpl,
        .SYS_profil                     = &notImpl,
        .SYS_statfs                     = &notImpl,
        .SYS_statfs64                   = @ptrCast(&krn.syscalls.statfs.statfs64),
        .SYS_fstatfs                    = &notImpl,
        .SYS_ioperm                     = &notImpl,
        .SYS_socketcall                 = @ptrCast(&krn.syscalls.socketcall.socketcall),
        .SYS_syslog                     = &notImpl,
        .SYS_setitimer                  = &notImpl,
        .SYS_getitimer                  = &notImpl,
        .SYS_stat                       = &notImpl,
        .SYS_lstat                      = &notImpl,
        .SYS_fstat                      = @ptrCast(&krn.syscalls.stat.fstat),
        .SYS_olduname                   = &notImpl,
        .SYS_iopl                       = &notImpl,
        .SYS_vhangup                    = &notImpl,
        .SYS_idle                       = &notImpl,
        .SYS_vm86old                    = &notImpl,
        .SYS_wait4                      = @ptrCast(&krn.syscalls.wait.wait4),
        .SYS_swapoff                    = &notImpl,
        .SYS_sysinfo                    = @ptrCast(&krn.syscalls.sysinfo.sysinfo),
        .SYS_ipc                        = &notImpl,
        .SYS_fsync                      = &notImpl,
        .SYS_sigreturn                  = @ptrCast(&krn.syscalls.sigaction.sigreturn),
        .SYS_clone                      = @ptrCast(&krn.syscalls.clone.clone),
        .SYS_setdomainname              = &notImpl,
        .SYS_uname                      = @ptrCast(&krn.syscalls.uname.uname),
        .SYS_modify_ldt                 = @ptrCast(&@import("thread.zig").modify_ldt),
        .SYS_adjtimex                   = &notImpl,
        .SYS_mprotect                   = @ptrCast(&krn.syscalls.mprotect.mprotect),
        .SYS_sigprocmask                = @ptrCast(&krn.syscalls.sigaction.sigprocmask),
        .SYS_create_module              = &notImpl,
        .SYS_init_module                = @ptrCast(&krn.syscalls.module.init_module),
        .SYS_finit_module               = @ptrCast(&krn.syscalls.module.finit_module),
        .SYS_delete_module              = @ptrCast(&krn.syscalls.module.delete_module),
        .SYS_get_kernel_syms            = &notImpl,
        .SYS_quotactl                   = &notImpl,
        .SYS_getpgid                    = @ptrCast(&krn.syscalls.id.getPGID),
        .SYS_fchdir                     = @ptrCast(&krn.syscalls.chdir.fchdir),
        .SYS_bdflush                    = &notImpl,
        .SYS_sysfs                      = &notImpl,
        .SYS_personality                = &notImpl,
        .SYS_afs_syscall                = &notImpl,
        .SYS_setfsuid                   = &notImpl,
        .SYS_setfsgid                   = &notImpl,
        .SYS__llseek                    = @ptrCast(&krn.syscalls.lseek.llseek),
        .SYS_getdents                   = @ptrCast(&krn.syscalls.getdents.getdents),
        .SYS__newselect                 = @ptrCast(&krn.syscalls.poll.newselect),
        .SYS_flock                      = &notImpl,
        .SYS_msync                      = &notImpl,
        .SYS_readv                      = @ptrCast(&krn.syscalls.read.readv),
        .SYS_writev                     = @ptrCast(&krn.syscalls.write.writev),
        .SYS_getsid                     = &notImpl,
        .SYS_fdatasync                  = &notImpl,
        .SYS__sysctl                    = &notImpl,
        .SYS_mlock                      = &notImpl,
        .SYS_munlock                    = &notImpl,
        .SYS_mlockall                   = &notImpl,
        .SYS_munlockall                 = &notImpl,
        .SYS_sched_setparam             = &notImpl,
        .SYS_sched_getparam             = &notImpl,
        .SYS_sched_setscheduler         = &notImpl,
        .SYS_sched_getscheduler         = &notImpl,
        .SYS_sched_yield                = &notImpl,
        .SYS_sched_get_priority_max     = &notImpl,
        .SYS_sched_get_priority_min     = &notImpl,
        .SYS_sched_rr_get_interval      = &notImpl,
        .SYS_nanosleep                  = @ptrCast(&krn.syscalls.sleep.nanosleep),
        .SYS_mremap                     = &notImpl,
        .SYS_setresuid                  = &notImpl,
        .SYS_getresuid                  = &notImpl,
        .SYS_vm86                       = &notImpl,
        .SYS_query_module               = &notImpl,
        .SYS_poll                       = @ptrCast(&krn.syscalls.poll.poll),
        .SYS_nfsservctl                 = &notImpl,
        .SYS_setresgid                  = &notImpl,
        .SYS_getresgid                  = &notImpl,
        .SYS_prctl                      = &notImpl,
        .SYS_rt_sigreturn               = @ptrCast(&krn.syscalls.sigaction.rt_sigreturn),
        .SYS_rt_sigaction               = @ptrCast(&krn.syscalls.sigaction.sigaction),
        .SYS_rt_sigprocmask             = @ptrCast(&krn.syscalls.sigaction.rt_sigprocmask),
        .SYS_rt_sigpending              = @ptrCast(&krn.syscalls.sigaction.rt_sigpending),
        .SYS_rt_sigtimedwait            = @ptrCast(&krn.syscalls.sigaction.rt_sigtimedwait),
        .SYS_rt_sigqueueinfo            = &notImpl,
        .SYS_rt_sigsuspend              = @ptrCast(&krn.syscalls.sigaction.rt_sigsuspend),
        .SYS_pread                      = @ptrCast(&krn.syscalls.read.pread),
        .SYS_preadv                     = @ptrCast(&krn.syscalls.read.preadv),
        .SYS_pwrite                     = &notImpl,
        .SYS_chown                      = &notImpl,
        .SYS_chown32                    = @ptrCast(&krn.syscalls.chown.chown32),
        .SYS_getcwd                     = @ptrCast(&krn.syscalls.getcwd.getcwd),
        .SYS_capget                     = &notImpl,
        .SYS_capset                     = &notImpl,
        .SYS_sigaltstack                = @ptrCast(&krn.syscalls.sigaction.sigaltstack),
        .SYS_sendfile                   = @ptrCast(&krn.syscalls.sendfile.sendfile),
        .SYS_sendfile64                 = @ptrCast(&krn.syscalls.sendfile.sendfile64),
        .SYS_getpmsg                    = &notImpl,
        .SYS_putpmsg                    = &notImpl,
        .SYS_vfork                      = &notImpl,
        .SYS_ugetrlimit                 = &notImpl,
        .SYS_mmap2                      = @ptrCast(&krn.syscalls.mmap.mmap2),
        .SYS_socketpair                 = @ptrCast(&krn.syscalls.socketcall.socketpair),
        .SYS_sendto                     = @ptrCast(&krn.syscalls.socketcall.sendto),
        .SYS_recvfrom                   = @ptrCast(&krn.syscalls.socketcall.recvfrom),
        .SYS_getuid32                   = @ptrCast(&krn.syscalls.id.getUID),
        .SYS_mknodat                    = &notImpl,
        .SYS_pwritev                    = @ptrCast(&krn.syscalls.write.pwritev),
        .SYS_getdents64                 = @ptrCast(&krn.syscalls.getdents.getdents64),
        .SYS_landlock_create_ruleset    = @ptrCast(&krn.syscalls.kshell.kshell),
        .SYS_setuid32                   = @ptrCast(&krn.syscalls.id.setUID),
        .SYS_setgid32                   = @ptrCast(&krn.syscalls.id.setGID),
        .SYS_getgid32                   = @ptrCast(&krn.syscalls.id.getUID),
        .SYS_stat64                     = @ptrCast(&krn.syscalls.stat.stat64),
        .SYS_lstat64                    = @ptrCast(&krn.syscalls.stat.lstat64),
        .SYS_fstat64                    = @ptrCast(&krn.syscalls.stat.fstat64),
        .SYS_fstatat64                  = @ptrCast(&krn.syscalls.stat.fstatat64),
        .SYS_openat                     = @ptrCast(&krn.syscalls.open.openat),
        .SYS_set_thread_area            = @ptrCast(&@import("thread.zig").set_thread_area),
        .SYS_set_tid_address            = @ptrCast(&@import("thread.zig").set_tid_address),
        .SYS_statx                      = @ptrCast(&krn.syscalls.statx.statx),
        .SYS_clock_gettime64            = @ptrCast(&krn.syscalls.clock.clock_gettime64),
        .SYS_clock_settime              = @ptrCast(&krn.syscalls.clock.clock_settime),
        .SYS_tkill                      = @ptrCast(&krn.syscalls.kill.tkill)
    });
};

pub const Syscall = enum(u10) {
    SYS_setup = 0,                  // 00
    SYS_exit,                       // 01
    SYS_fork,                       // 02
    SYS_read,                       // 03
    SYS_write,                      // 04
    SYS_open,                       // 05
    SYS_close,                      // 06
    SYS_waitpid,                    // 07
    SYS_creat,                      // 08
    SYS_link,                       // 09
    SYS_unlink,                     // 10
    SYS_execve,                     // 11
    SYS_chdir,                      // 12
    SYS_time,                       // 13
    SYS_mknod,                      // 14
    SYS_chmod,                      // 15
    SYS_lchown,                     // 16
    SYS_break,                      // 17
    SYS_oldstat,                    // 18
    SYS_lseek,                      // 19
    SYS_getpid,                     // 20
    SYS_mount,                      // 21
    SYS_umount,                     // 22
    SYS_setuid,                     // 23
    SYS_getuid,                     // 24
    SYS_stime,                      // 25
    SYS_ptrace,                     // 26
    SYS_alarm,                      // 27
    SYS_oldfstat,                   // 28
    SYS_pause,                      // 29
    SYS_utime,                      // 30
    SYS_stty,                       // 31
    SYS_gtty,                       // 32
    SYS_access,                     // 33
    SYS_nice,                       // 34
    SYS_ftime,                      // 35
    SYS_sync,                       // 36
    SYS_kill,                       // 37
    SYS_rename,                     // 38
    SYS_mkdir,                      // 39
    SYS_rmdir,                      // 40
    SYS_dup,                        // 41
    SYS_pipe,                       // 42
    SYS_times,                      // 43
    SYS_prof,                       // 44
    SYS_brk,                        // 45
    SYS_setgid,                     // 46
    SYS_getgid,                     // 47
    SYS_signal,                     // 48
    SYS_geteuid,                    // 49
    SYS_getegid,                    // 50
    SYS_acct,                       // 51
    SYS_umount2,                    // 52
    SYS_lock,                       // 53
    SYS_ioctl,                      // 54
    SYS_fcntl,                      // 55
    SYS_mpx,                        // 56
    SYS_setpgid,                    // 57
    SYS_ulimit,                     // 58
    SYS_oldolduname,                // 59
    SYS_umask,                      // 60
    SYS_chroot,                     // 61
    SYS_ustat,                      // 62
    SYS_dup2,                       // 63
    SYS_getppid,                    // 64
    SYS_getpgrp,                    // 65
    SYS_setsid,                     // 66
    SYS_sigaction,                  // 67
    SYS_sgetmask,                   // 68
    SYS_ssetmask,                   // 69
    SYS_setreuid,                   // 70
    SYS_setregid,                   // 71
    SYS_sigsuspend,                 // 72
    SYS_sigpending,                 // 73
    SYS_sethostname,                // 74
    SYS_setrlimit,                  // 75
    SYS_getrlimit,                  // 76
    SYS_getrusage,                  // 77
    SYS_gettimeofday,               // 78
    SYS_settimeofday,               // 79
    SYS_getgroups,                  // 80
    SYS_setgroups,                  // 81
    SYS_select,                     // 82
    SYS_symlink,                    // 83
    SYS_oldlstat,                   // 84
    SYS_readlink,                   // 85
    SYS_uselib,                     // 86
    SYS_swapon,                     // 87
    SYS_reboot,                     // 88
    SYS_readdir,                    // 89
    SYS_mmap,                       // 90
    SYS_munmap,                     // 91
    SYS_truncate,                   // 92
    SYS_ftruncate,                  // 93
    SYS_fchmod,                     // 94
    SYS_fchown,                     // 95
    SYS_getpriority,                // 96
    SYS_setpriority,                // 97
    SYS_profil,                     // 98
    SYS_statfs,                     // 99
    SYS_fstatfs,                    // 100
    SYS_ioperm,                     // 101
    SYS_socketcall,                 // 102
    SYS_syslog,                     // 103
    SYS_setitimer,                  // 104
    SYS_getitimer,                  // 105
    SYS_stat,                       // 106
    SYS_lstat,                      // 107
    SYS_fstat,                      // 108
    SYS_olduname,                   // 109
    SYS_iopl,                       // 110
    SYS_vhangup,                    // 111
    SYS_idle,                       // 112
    SYS_vm86old,                    // 113
    SYS_wait4,                      // 114
    SYS_swapoff,                    // 115
    SYS_sysinfo,                    // 116
    SYS_ipc,                        // 117
    SYS_fsync,                      // 118
    SYS_sigreturn,                  // 119
    SYS_clone,                      // 120
    SYS_setdomainname,              // 121
    SYS_uname,                      // 122
    SYS_modify_ldt,                 // 123
    SYS_adjtimex,                   // 124
    SYS_mprotect,                   // 125
    SYS_sigprocmask,                // 126
    SYS_create_module,              // 127
    SYS_init_module,                // 128
    SYS_delete_module,              // 129
    SYS_get_kernel_syms,            // 130
    SYS_quotactl,                   // 131
    SYS_getpgid,                    // 132
    SYS_fchdir,                     // 133
    SYS_bdflush,                    // 134
    SYS_sysfs,                      // 135
    SYS_personality,                // 136
    SYS_afs_syscall,                // 137
    SYS_setfsuid,                   // 138
    SYS_setfsgid,                   // 139
    SYS__llseek,                    // 140
    SYS_getdents,                   // 141
    SYS__newselect,                 // 142
    SYS_flock,                      // 143
    SYS_msync,                      // 144
    SYS_readv,                      // 145
    SYS_writev,                     // 146
    SYS_getsid,                     // 147
    SYS_fdatasync,                  // 148
    SYS__sysctl,                    // 149
    SYS_mlock,                      // 150
    SYS_munlock,                    // 151
    SYS_mlockall,                   // 152
    SYS_munlockall,                 // 153
    SYS_sched_setparam,             // 154
    SYS_sched_getparam,             // 155
    SYS_sched_setscheduler,         // 156
    SYS_sched_getscheduler,         // 157
    SYS_sched_yield,                // 158
    SYS_sched_get_priority_max,     // 159
    SYS_sched_get_priority_min,     // 160
    SYS_sched_rr_get_interval,      // 161
    SYS_nanosleep,                  // 162
    SYS_mremap,                     // 163
    SYS_setresuid,                  // 164
    SYS_getresuid,                  // 165
    SYS_vm86,                       // 166
    SYS_query_module,               // 167
    SYS_poll,                       // 168
    SYS_nfsservctl,                 // 169
    SYS_setresgid,                  // 170
    SYS_getresgid,                  // 171
    SYS_prctl,                      // 172
    SYS_rt_sigreturn,               // 173
    SYS_rt_sigaction,               // 174
    SYS_rt_sigprocmask,             // 175
    SYS_rt_sigpending,              // 176
    SYS_rt_sigtimedwait,            // 177
    SYS_rt_sigqueueinfo,            // 178
    SYS_rt_sigsuspend,              // 179
    SYS_pread,                      // 180
    SYS_pwrite,                     // 181
    SYS_chown,                      // 182
    SYS_getcwd,                     // 183
    SYS_capget,                     // 184
    SYS_capset,                     // 185
    SYS_sigaltstack,                // 186
    SYS_sendfile,                   // 187
    SYS_getpmsg,                    // 188
    SYS_putpmsg,                    // 189
    SYS_vfork,                      // 190
    SYS_ugetrlimit = 191,
    SYS_mmap2 = 192,
    SYS_truncate64 = 193,
    SYS_ftruncate64 = 194,
    SYS_stat64 = 195,
    SYS_lstat64 = 196,
    SYS_fstat64 = 197,
    SYS_lchown32 = 198,
    SYS_getuid32 = 199,
    SYS_getgid32 = 200,
    SYS_geteuid32 = 201,
    SYS_getegid32 = 202,
    SYS_setreuid32 = 203,
    SYS_setregid32 = 204,
    SYS_getgroups32 = 205,
    SYS_setgroups32 = 206,
    SYS_fchown32 = 207,
    SYS_setresuid32 = 208,
    SYS_getresuid32 = 209,
    SYS_setresgid32 = 210,
    SYS_getresgid32 = 211,
    SYS_chown32 = 212,
    SYS_setuid32 = 213,
    SYS_setgid32 = 214,
    SYS_setfsuid32 = 215,
    SYS_setfsgid32 = 216,
    SYS_pivot_root = 217,
    SYS_mincore = 218,
    SYS_madvise = 219,
    SYS_getdents64 = 220,
    SYS_fcntl64 = 221,
    SYS_gettid = 224,
    SYS_readahead = 225,
    SYS_setxattr = 226,
    SYS_lsetxattr = 227,
    SYS_fsetxattr = 228,
    SYS_getxattr = 229,
    SYS_lgetxattr = 230,
    SYS_fgetxattr = 231,
    SYS_listxattr = 232,
    SYS_llistxattr = 233,
    SYS_flistxattr = 234,
    SYS_removexattr = 235,
    SYS_lremovexattr = 236,
    SYS_fremovexattr = 237,
    SYS_tkill = 238,
    SYS_sendfile64 = 239,
    SYS_futex = 240,
    SYS_sched_setaffinity = 241,
    SYS_sched_getaffinity = 242,
    SYS_set_thread_area = 243,
    SYS_get_thread_area = 244,
    SYS_io_setup = 245,
    SYS_io_destroy = 246,
    SYS_io_getevents = 247,
    SYS_io_submit = 248,
    SYS_io_cancel = 249,
    SYS_fadvise64 = 250,
    SYS_exit_group = 252,
    SYS_lookup_dcookie = 253,
    SYS_epoll_create = 254,
    SYS_epoll_ctl = 255,
    SYS_epoll_wait = 256,
    SYS_remap_file_pages = 257,
    SYS_set_tid_address = 258,
    SYS_timer_create = 259,
    SYS_timer_settime = 260,
    SYS_timer_gettime = 261,
    SYS_timer_getoverrun = 262,
    SYS_timer_delete = 263,
    SYS_clock_settime = 264,
    SYS_clock_gettime = 265,
    SYS_clock_getres = 266,
    SYS_clock_nanosleep = 267,
    SYS_statfs64 = 268,
    SYS_fstatfs64 = 269,
    SYS_tgkill = 270,
    SYS_utimes = 271,
    SYS_fadvise64_64 = 272,
    SYS_vserver = 273,
    SYS_mbind = 274,
    SYS_get_mempolicy = 275,
    SYS_set_mempolicy = 276,
    SYS_mq_open = 277,
    SYS_mq_unlink = 278,
    SYS_mq_timedsend = 279,
    SYS_mq_timedreceive = 280,
    SYS_mq_notify = 281,
    SYS_mq_getsetattr = 282,
    SYS_kexec_load = 283,
    SYS_waitid = 284,
    SYS_add_key = 286,
    SYS_request_key = 287,
    SYS_keyctl = 288,
    SYS_ioprio_set = 289,
    SYS_ioprio_get = 290,
    SYS_inotify_init = 291,
    SYS_inotify_add_watch = 292,
    SYS_inotify_rm_watch = 293,
    SYS_migrate_pages = 294,
    SYS_openat = 295,
    SYS_mkdirat = 296,
    SYS_mknodat = 297,
    SYS_fchownat = 298,
    SYS_futimesat = 299,
    SYS_fstatat64 = 300,
    SYS_unlinkat = 301,
    SYS_renameat = 302,
    SYS_linkat = 303,
    SYS_symlinkat = 304,
    SYS_readlinkat = 305,
    SYS_fchmodat = 306,
    SYS_faccessat = 307,
    SYS_pselect6 = 308,
    SYS_ppoll = 309,
    SYS_unshare = 310,
    SYS_set_robust_list = 311,
    SYS_get_robust_list = 312,
    SYS_splice = 313,
    SYS_sync_file_range = 314,
    SYS_tee = 315,
    SYS_vmsplice = 316,
    SYS_move_pages = 317,
    SYS_getcpu = 318,
    SYS_epoll_pwait = 319,
    SYS_utimensat = 320,
    SYS_signalfd = 321,
    SYS_timerfd_create = 322,
    SYS_eventfd = 323,
    SYS_fallocate = 324,
    SYS_timerfd_settime = 325,
    SYS_timerfd_gettime = 326,
    SYS_signalfd4 = 327,
    SYS_eventfd2 = 328,
    SYS_epoll_create1 = 329,
    SYS_dup3 = 330,
    SYS_pipe2 = 331,
    SYS_inotify_init1 = 332,
    SYS_preadv = 333,
    SYS_pwritev = 334,
    SYS_rt_tgsigqueueinfo = 335,
    SYS_perf_event_open = 336,
    SYS_recvmmsg = 337,
    SYS_fanotify_init = 338,
    SYS_fanotify_mark = 339,
    SYS_prlimit64 = 340,
    SYS_name_to_handle_at = 341,
    SYS_open_by_handle_at = 342,
    SYS_clock_adjtime = 343,
    SYS_syncfs = 344,
    SYS_sendmmsg = 345,
    SYS_setns = 346,
    SYS_process_vm_readv = 347,
    SYS_process_vm_writev = 348,
    SYS_kcmp = 349,
    SYS_finit_module = 350,
    SYS_sched_setattr = 351,
    SYS_sched_getattr = 352,
    SYS_renameat2 = 353,
    SYS_seccomp = 354,
    SYS_getrandom = 355,
    SYS_memfd_create = 356,
    SYS_bpf = 357,
    SYS_execveat = 358,
    SYS_socket = 359,
    SYS_socketpair = 360,
    SYS_bind = 361,
    SYS_connect = 362,
    SYS_listen = 363,
    SYS_accept4 = 364,
    SYS_getsockopt = 365,
    SYS_setsockopt = 366,
    SYS_getsockname = 367,
    SYS_getpeername = 368,
    SYS_sendto = 369,
    SYS_sendmsg = 370,
    SYS_recvfrom = 371,
    SYS_recvmsg = 372,
    SYS_shutdown = 373,
    SYS_userfaultfd = 374,
    SYS_membarrier = 375,
    SYS_mlock2 = 376,
    SYS_copy_file_range = 377,
    SYS_preadv2 = 378,
    SYS_pwritev2 = 379,
    SYS_pkey_mprotect = 380,
    SYS_pkey_alloc = 381,
    SYS_pkey_free = 382,
    SYS_statx = 383,
    SYS_arch_prctl = 384,
    SYS_io_pgetevents = 385,
    SYS_rseq = 386,
    SYS_semget = 393,
    SYS_semctl = 394,
    SYS_shmget = 395,
    SYS_shmctl = 396,
    SYS_shmat = 397,
    SYS_shmdt = 398,
    SYS_msgget = 399,
    SYS_msgsnd = 400,
    SYS_msgrcv = 401,
    SYS_msgctl = 402,
    SYS_clock_gettime64 = 403,
    SYS_clock_settime64 = 404,
    SYS_clock_adjtime64 = 405,
    SYS_clock_getres_time64 = 406,
    SYS_clock_nanosleep_time64 = 407,
    SYS_timer_gettime64 = 408,
    SYS_timer_settime64 = 409,
    SYS_timerfd_gettime64 = 410,
    SYS_timerfd_settime64 = 411,
    SYS_utimensat_time64 = 412,
    SYS_pselect6_time64 = 413,
    SYS_ppoll_time64 = 414,
    SYS_io_pgetevents_time64 = 416,
    SYS_recvmmsg_time64 = 417,
    SYS_mq_timedsend_time64 = 418,
    SYS_mq_timedreceive_time64 = 419,
    SYS_semtimedop_time64 = 420,
    SYS_rt_sigtimedwait_time64 = 421,
    SYS_futex_time64 = 422,
    SYS_sched_rr_get_interval_time64 = 423,
    SYS_pidfd_send_signal = 424,
    SYS_io_uring_setup = 425,
    SYS_io_uring_enter = 426,
    SYS_io_uring_register = 427,
    SYS_open_tree = 428,
    SYS_move_mount = 429,
    SYS_fsopen = 430,
    SYS_fsconfig = 431,
    SYS_fsmount = 432,
    SYS_fspick = 433,
    SYS_pidfd_open = 434,
    SYS_clone3 = 435,
    SYS_close_range = 436,
    SYS_openat2 = 437,
    SYS_pidfd_getfd = 438,
    SYS_faccessat2 = 439,
    SYS_process_madvise = 440,
    SYS_epoll_pwait2 = 441,
    SYS_mount_setattr = 442,
    SYS_quotactl_fd = 443,
    SYS_landlock_create_ruleset = 444,
    SYS_landlock_add_rule = 445,
    SYS_landlock_restrict_self = 446,
    SYS_memfd_secret = 447,
    SYS_process_mrelease = 448,
    SYS_futex_waitv = 449,
    SYS_set_mempolicy_home_node = 450,
    SYS_cachestat = 451,
    SYS_fchmodat2 = 452,
    SYS_map_shadow_stack = 453,
    SYS_futex_wake = 454,
    SYS_futex_wait = 455,
    SYS_futex_requeue = 456,
    SYS_statmount = 457,
    SYS_listmount = 458,
    SYS_lsm_get_self_attr = 459,
    SYS_lsm_set_self_attr = 460,
    SYS_lsm_list_modules = 461,
    SYS_mseal = 462,
    _
};
