const std = @import("std");
const ScanCode = @import("./kbd.zig").ScanCode;
const KeymapEntry = @import("./kbd.zig").KeymapEntry;

pub const keymap_us = std.EnumMap(
    ScanCode,
    KeymapEntry
).init(.{
    .K_ESC          = .{ .normal = 27, },
    .K_1            = .{ .normal = '1', .shift = '!', },
    .K_2            = .{ .normal = '2', .shift = '@', },
    .K_3            = .{ .normal = '3', .shift = '#', },
    .K_4            = .{ .normal = '4', .shift = '$', },
    .K_5            = .{ .normal = '5', .shift = '%', },
    .K_6            = .{ .normal = '6', .shift = '^', .ctrl = 30, },
    .K_7            = .{ .normal = '7', .shift = '&', },
    .K_8            = .{ .normal = '8', .shift = '*', },
    .K_9            = .{ .normal = '9', .shift = '(', },
    .K_0            = .{ .normal = '0', .shift = ')', },
    .K_MINUS        = .{ .normal = '-', .shift = '_', },
    .K_EQUALS       = .{ .normal = '=', .shift = '+', .ctrl = 31, },
    .K_BACKSPACE    = .{ .normal = 8, },
    .K_TAB          = .{ .normal = '\t', },
    .K_Q            = .{ .normal = 'q', .shift = 'Q', .ctrl = 17, }, 
    .K_W            = .{ .normal = 'w', .shift = 'W', .ctrl = 23, }, 
    .K_E            = .{ .normal = 'e', .shift = 'E', .ctrl = 5, }, 
    .K_R            = .{ .normal = 'r', .shift = 'R', .ctrl = 18, }, 
    .K_T            = .{ .normal = 't', .shift = 'T', .ctrl = 20, }, 
    .K_Y            = .{ .normal = 'y', .shift = 'Y', .ctrl = 25, }, 
    .K_U            = .{ .normal = 'u', .shift = 'U', .ctrl = 21, }, 
    .K_I            = .{ .normal = 'i', .shift = 'I', .ctrl = 9, }, 
    .K_O            = .{ .normal = 'o', .shift = 'O', .ctrl = 15, }, 
    .K_P            = .{ .normal = 'p', .shift = 'P', .ctrl = 16, },
    .K_OSQB         = .{ .normal = '[', .shift = '{' }, 
    .K_CSQB         = .{ .normal = ']', .shift = '}' }, 
    .K_ENTER        = .{ .normal = '\r', },

    .K_A            = .{ .normal = 'a', .shift = 'A', .ctrl = 1, },
    .K_S            = .{ .normal = 's', .shift = 'S', .ctrl = 19, },
    .K_D            = .{ .normal = 'd', .shift = 'D', .ctrl = 4, },
    .K_F            = .{ .normal = 'f', .shift = 'F', .ctrl = 6, },
    .K_G            = .{ .normal = 'g', .shift = 'G', .ctrl = 7, },
    .K_H            = .{ .normal = 'h', .shift = 'H', .ctrl = 8, },
    .K_J            = .{ .normal = 'j', .shift = 'J', .ctrl = 10, },
    .K_K            = .{ .normal = 'k', .shift = 'K', .ctrl = 11, },
    .K_L            = .{ .normal = 'l', .shift = 'L', .ctrl = 12, },
    .K_SEMICOL      = .{ .normal = ';', .shift = ':', },
    .K_QUOTE        = .{ .normal = '\'', .shift = '"', },
    .K_BCKQUOTE     = .{ .normal = '`', .shift = '~', },

    
    .K_BCKSL        = .{ .normal = '\\', .shift = '|', .ctrl = 28, }, 
    .K_Z            = .{ .normal = 'z', .shift = 'Z', .ctrl = 26, }, 
    .K_X            = .{ .normal = 'x', .shift = 'X', .ctrl = 24, }, 
    .K_C            = .{ .normal = 'c', .shift = 'C', .ctrl = 3, }, 
    .K_V            = .{ .normal = 'v', .shift = 'V', .ctrl = 22, }, 
    .K_B            = .{ .normal = 'b', .shift = 'B', .ctrl = 2, }, 
    .K_N            = .{ .normal = 'n', .shift = 'N', .ctrl = 14, }, 
    .K_M            = .{ .normal = 'm', .shift = 'M', .ctrl = 13, }, 
    .K_COMMA        = .{ .normal = ',', .shift = '<', }, 
    .K_DOT          = .{ .normal = '.', .shift = '>', }, 
    .K_SLASH        = .{ .normal = '/', .shift = '?', },

    .K_WHITESPACE   = .{ .normal = ' ', },

    .K_KPAD_MINUS   = .{ .normal = '-', },
    .K_KPAD_PLUS    = .{ .normal = '+', },
    .K_KPAD_STAR    = .{ .normal = '*', },

    .K_LLALT        = .{ .normal = '<', .shift = '>', },
});

pub const keymap_de = std.EnumMap(
    ScanCode,
    KeymapEntry
).init(.{
    .K_ESC          = .{ .normal = 27, },
    .K_1            = .{ .normal = '1', .shift = '!', },
    .K_2            = .{ .normal = '2', .shift = '"', },
    .K_3            = .{ .normal = '3', .shift = '§', },
    .K_4            = .{ .normal = '4', .shift = '$', },
    .K_5            = .{ .normal = '5', .shift = '%', },
    .K_6            = .{ .normal = '6', .shift = '&', },
    .K_7            = .{ .normal = '7', .shift = '/', },
    .K_8            = .{ .normal = '8', .shift = '(', },
    .K_9            = .{ .normal = '9', .shift = ')', },
    .K_0            = .{ .normal = '0', .shift = '=', },
    .K_MINUS        = .{ .normal = 0xDF, .shift = '?', },
    .K_EQUALS       = .{ .normal = 0x92, .shift = '`', },
    .K_BACKSPACE    = .{ .normal = 8, },
    .K_TAB          = .{ .normal = '\t', },
    .K_Q            = .{ .normal = 'q', .shift = 'Q', }, 
    .K_W            = .{ .normal = 'w', .shift = 'W', }, 
    .K_E            = .{ .normal = 'e', .shift = 'E', }, 
    .K_R            = .{ .normal = 'r', .shift = 'R', }, 
    .K_T            = .{ .normal = 't', .shift = 'T', }, 
    .K_Y            = .{ .normal = 'z', .shift = 'Z', }, 
    .K_U            = .{ .normal = 'u', .shift = 'U', }, 
    .K_I            = .{ .normal = 'i', .shift = 'I', }, 
    .K_O            = .{ .normal = 'o', .shift = 'O', }, 
    .K_P            = .{ .normal = 'p', .shift = 'P', },
    .K_OSQB         = .{ .normal = 0xFC, .shift = 0xDC }, 
    .K_CSQB         = .{ .normal = '+', .shift = '*' }, 
    .K_ENTER        = .{ .normal = '\n', },

    .K_A            = .{ .normal = 'a', .shift = 'A', .ctrl = 1, },
    .K_S            = .{ .normal = 's', .shift = 'S', },
    .K_D            = .{ .normal = 'd', .shift = 'D', },
    .K_F            = .{ .normal = 'f', .shift = 'F', },
    .K_G            = .{ .normal = 'g', .shift = 'G', },
    .K_H            = .{ .normal = 'h', .shift = 'H', },
    .K_J            = .{ .normal = 'j', .shift = 'J', },
    .K_K            = .{ .normal = 'k', .shift = 'K', },
    .K_L            = .{ .normal = 'l', .shift = 'L', .ctrl = 12, },
    .K_SEMICOL      = .{ .normal = 0xF6, .shift = 0xD6, },
    .K_QUOTE        = .{ .normal = 0xE4, .shift = 0xC4, },
    .K_BCKQUOTE     = .{ .normal = '^', .shift = 0xB0, },

    
    .K_BCKSL        = .{ .normal = '#', .shift = '\'', }, 
    .K_Z            = .{ .normal = 'y', .shift = 'Y', }, 
    .K_X            = .{ .normal = 'x', .shift = 'X', }, 
    .K_C            = .{ .normal = 'c', .shift = 'C', .ctrl = 3, }, 
    .K_V            = .{ .normal = 'v', .shift = 'V', }, 
    .K_B            = .{ .normal = 'b', .shift = 'B', }, 
    .K_N            = .{ .normal = 'n', .shift = 'N', }, 
    .K_M            = .{ .normal = 'm', .shift = 'M', }, 
    .K_COMMA        = .{ .normal = ',', .shift = ';', }, 
    .K_DOT          = .{ .normal = '.', .shift = ':', }, 
    .K_SLASH        = .{ .normal = '-', .shift = '_', },

    .K_WHITESPACE   = .{ .normal = ' ', },

    .K_KPAD_MINUS   = .{ .normal = '-', },
    .K_KPAD_PLUS    = .{ .normal = '+', },
    .K_KPAD_STAR    = .{ .normal = '*', },

    .K_LLALT        = .{ .normal = '<', .shift = '>', },
    .K_DEL          = .{ .normal = 127, },
});
