pub const EPERM	    = 1;	// Operation not permitted
pub const ENOENT    = 2;	// No such file or directory
pub const ESRCH     = 3;	// No such process
pub const EINTR	    = 4;	// Interrupted system call
pub const EIO	    = 5;	// I/O error
pub const ENXIO	    = 6;	// No such device or address 
pub const E2BIG	    = 7;	// Argument list too long
pub const ENOEXEC   = 8;	// Exec format error
pub const EBADF	    = 9;	// Bad file number
pub const ECHILD    = 10;	// No child processes
pub const EAGAIN    = 11;	// Try again
pub const ENOMEM    = 12;	// Out of memory
pub const EACCES    = 13;	// Permission denied
pub const EFAULT    = 14;	// Bad address
pub const ENOTBLK   = 15;	// Block device required
pub const EBUSY	    = 16;	// Device or resource busy
pub const EEXIST    = 17;	// File exists
pub const EXDEV	    = 18;	// Cross-device link
pub const ENODEV    = 19;	// No such device
pub const ENOTDIR   = 20;	// Not a directory
pub const EISDIR    = 21;	// Is a directory
pub const EINVAL    = 22;	// Invalid argument
pub const ENFILE    = 23;	// File table overflow
pub const EMFILE    = 24;	// Too many open files
pub const ENOTTY    = 25;	// Not a typewriter
pub const ETXTBSY   = 26;	// Text file busy
pub const EFBIG	    = 27;	// File too large
pub const ENOSPC    = 28;	// No space left on device
pub const ESPIPE    = 29;	// Illegal seek
pub const EROFS	    = 30;	// Read-only file system
pub const EMLINK    = 31;	// Too many links
pub const EPIPE	    = 32;	// Broken pipe
pub const EDOM	    = 33;	// Math argument out of domain of func
pub const ERANGE    = 34;	// Math result not representable
