const std = @import("std");
const arch = @import("arch");
const krn = @import("../main.zig");

pub const SyscallHandler = fn (
    state: *arch.Regs,
    a1: u32,
    a2: u32,
    a3: u32,
    a4: u32,
    a5: u32,
    a6: u32,
) i32;

fn notImpl(state: *arch.Regs, _: u32, _: u32, _: u32, _: u32, _: u32, _: u32) i32 {
    krn.logger.WARN("syscall {d} {s} is not implemented", .{
        state.eax,
        @tagName(@as(Syscall, @enumFromInt(state.eax)))
    });
    return 0;
}

pub const SyscallTable = brk: {
    @setEvalBranchQuota(1500);
    break :brk std.EnumMap(Syscall, *const SyscallHandler).init(.{
        .SYS_setup                      = &notImpl,
        .SYS_exit                       = @ptrCast(&@import("exit.zig").exit),
        .SYS_fork                       = @ptrCast(&@import("fork.zig").fork),
        .SYS_read                       = &notImpl,
        .SYS_write                      = @ptrCast(&@import("write.zig").write),
        .SYS_open                       = &notImpl,
        .SYS_close                      = &notImpl,
        .SYS_waitpid                    = &notImpl,
        .SYS_creat                      = &notImpl,
        .SYS_link                       = &notImpl,
        .SYS_unlink                     = &notImpl,
        .SYS_execve                     = &notImpl,
        .SYS_chdir                      = &notImpl,
        .SYS_time                       = &notImpl,
        .SYS_mknod                      = &notImpl,
        .SYS_chmod                      = &notImpl,
        .SYS_lchown                     = &notImpl,
        .SYS_break                      = &notImpl,
        .SYS_oldstat                    = &notImpl,
        .SYS_lseek                      = &notImpl,
        .SYS_getpid                     = @ptrCast(&@import("../sched/process.zig").getPID),
        .SYS_mount                      = &notImpl,
        .SYS_umount                     = &notImpl,
        .SYS_setuid                     = @ptrCast(&@import("../sched/process.zig").setUID),
        .SYS_getuid                     = @ptrCast(&@import("../sched/process.zig").getUID),
        .SYS_stime                      = &notImpl,
        .SYS_ptrace                     = &notImpl,
        .SYS_alarm                      = &notImpl,
        .SYS_oldfstat                   = &notImpl,
        .SYS_pause                      = &notImpl,
        .SYS_utime                      = &notImpl,
        .SYS_stty                       = &notImpl,
        .SYS_gtty                       = &notImpl,
        .SYS_access                     = &notImpl,
        .SYS_nice                       = &notImpl,
        .SYS_ftime                      = &notImpl,
        .SYS_sync                       = &notImpl,
        .SYS_kill                       = @ptrCast(&@import("kill.zig").kill),
        .SYS_rename                     = &notImpl,
        .SYS_mkdir                      = &notImpl,
        .SYS_rmdir                      = &notImpl,
        .SYS_dup                        = &notImpl,
        .SYS_pipe                       = &notImpl,
        .SYS_times                      = &notImpl,
        .SYS_prof                       = &notImpl,
        .SYS_brk                        = &notImpl,
        .SYS_setgid                     = @ptrCast(&@import("../sched/process.zig").setGID),
        .SYS_getgid                     = @ptrCast(&@import("../sched/process.zig").getPID),
        .SYS_signal                     = &notImpl,
        .SYS_geteuid                    = &notImpl,
        .SYS_getegid                    = &notImpl,
        .SYS_acct                       = &notImpl,
        .SYS_umount2                    = &notImpl,
        .SYS_lock                       = &notImpl,
        .SYS_ioctl                      = &notImpl,
        .SYS_fcntl                      = &notImpl,
        .SYS_mpx                        = &notImpl,
        .SYS_setpgid                    = @ptrCast(&@import("../sched/process.zig").setPGID),
        .SYS_ulimit                     = &notImpl,
        .SYS_oldolduname                = &notImpl,
        .SYS_umask                      = &notImpl,
        .SYS_chroot                     = &notImpl,
        .SYS_ustat                      = &notImpl,
        .SYS_dup2                       = &notImpl,
        .SYS_getppid                    = @ptrCast(&@import("../sched/process.zig").getPPID),
        .SYS_getpgrp                    = &notImpl,
        .SYS_setsid                     = &notImpl,
        .SYS_sigaction                  = &notImpl,
        .SYS_sgetmask                   = &notImpl,
        .SYS_ssetmask                   = &notImpl,
        .SYS_setreuid                   = &notImpl,
        .SYS_setregid                   = &notImpl,
        .SYS_sigsuspend                 = &notImpl,
        .SYS_sigpending                 = &notImpl,
        .SYS_sethostname                = &notImpl,
        .SYS_setrlimit                  = &notImpl,
        .SYS_getrlimit                  = &notImpl,
        .SYS_getrusage                  = &notImpl,
        .SYS_gettimeofday               = &notImpl,
        .SYS_settimeofday               = &notImpl,
        .SYS_getgroups                  = &notImpl,
        .SYS_setgroups                  = &notImpl,
        .SYS_select                     = &notImpl,
        .SYS_symlink                    = &notImpl,
        .SYS_oldlstat                   = &notImpl,
        .SYS_readlink                   = &notImpl,
        .SYS_uselib                     = &notImpl,
        .SYS_swapon                     = &notImpl,
        .SYS_reboot                     = &notImpl,
        .SYS_readdir                    = &notImpl,
        .SYS_mmap                       = &notImpl,
        .SYS_munmap                     = &notImpl,
        .SYS_truncate                   = &notImpl,
        .SYS_ftruncate                  = &notImpl,
        .SYS_fchmod                     = &notImpl,
        .SYS_fchown                     = &notImpl,
        .SYS_getpriority                = &notImpl,
        .SYS_setpriority                = &notImpl,
        .SYS_profil                     = &notImpl,
        .SYS_statfs                     = &notImpl,
        .SYS_fstatfs                    = &notImpl,
        .SYS_ioperm                     = &notImpl,
        .SYS_socketcall                 = &notImpl,
        .SYS_syslog                     = &notImpl,
        .SYS_setitimer                  = &notImpl,
        .SYS_getitimer                  = &notImpl,
        .SYS_stat                       = &notImpl,
        .SYS_lstat                      = &notImpl,
        .SYS_fstat                      = &notImpl,
        .SYS_olduname                   = &notImpl,
        .SYS_iopl                       = &notImpl,
        .SYS_vhangup                    = &notImpl,
        .SYS_idle                       = &notImpl,
        .SYS_vm86old                    = &notImpl,
        .SYS_wait4                      = @ptrCast(&@import("wait.zig").wait4),
        .SYS_swapoff                    = &notImpl,
        .SYS_sysinfo                    = &notImpl,
        .SYS_ipc                        = &notImpl,
        .SYS_fsync                      = &notImpl,
        .SYS_sigreturn                  = &notImpl,
        .SYS_clone                      = &notImpl,
        .SYS_setdomainname              = &notImpl,
        .SYS_uname                      = &notImpl,
        .SYS_modify_ldt                 = &notImpl,
        .SYS_adjtimex                   = &notImpl,
        .SYS_mprotect                   = &notImpl,
        .SYS_sigprocmask                = &notImpl,
        .SYS_create_module              = &notImpl,
        .SYS_init_module                = &notImpl,
        .SYS_delete_module              = &notImpl,
        .SYS_get_kernel_syms            = &notImpl,
        .SYS_quotactl                   = &notImpl,
        .SYS_getpgid                    = @ptrCast(&@import("../sched/process.zig").getPGID),
        .SYS_fchdir                     = &notImpl,
        .SYS_bdflush                    = &notImpl,
        .SYS_sysfs                      = &notImpl,
        .SYS_personality                = &notImpl,
        .SYS_afs_syscall                = &notImpl,
        .SYS_setfsuid                   = &notImpl,
        .SYS_setfsgid                   = &notImpl,
        .SYS__llseek                    = &notImpl,
        .SYS_getdents                   = &notImpl,
        .SYS__newselect                 = &notImpl,
        .SYS_flock                      = &notImpl,
        .SYS_msync                      = &notImpl,
        .SYS_readv                      = &notImpl,
        .SYS_writev                     = &notImpl,
        .SYS_getsid                     = &notImpl,
        .SYS_fdatasync                  = &notImpl,
        .SYS__sysctl                    = &notImpl,
        .SYS_mlock                      = &notImpl,
        .SYS_munlock                    = &notImpl,
        .SYS_mlockall                   = &notImpl,
        .SYS_munlockall                 = &notImpl,
        .SYS_sched_setparam             = &notImpl,
        .SYS_sched_getparam             = &notImpl,
        .SYS_sched_setscheduler         = &notImpl,
        .SYS_sched_getscheduler         = &notImpl,
        .SYS_sched_yield                = &notImpl,
        .SYS_sched_get_priority_max     = &notImpl,
        .SYS_sched_get_priority_min     = &notImpl,
        .SYS_sched_rr_get_interval      = &notImpl,
        .SYS_nanosleep                  = &notImpl,
        .SYS_mremap                     = &notImpl,
        .SYS_setresuid                  = &notImpl,
        .SYS_getresuid                  = &notImpl,
        .SYS_vm86                       = &notImpl,
        .SYS_query_module               = &notImpl,
        .SYS_poll                       = &notImpl,
        .SYS_nfsservctl                 = &notImpl,
        .SYS_setresgid                  = &notImpl,
        .SYS_getresgid                  = &notImpl,
        .SYS_prctl                      = &notImpl,
        .SYS_rt_sigreturn               = &notImpl,
        .SYS_rt_sigaction               = &notImpl,
        .SYS_rt_sigprocmask             = &notImpl,
        .SYS_rt_sigpending              = &notImpl,
        .SYS_rt_sigtimedwait            = &notImpl,
        .SYS_rt_sigqueueinfo            = &notImpl,
        .SYS_rt_sigsuspend              = &notImpl,
        .SYS_pread                      = &notImpl,
        .SYS_pwrite                     = &notImpl,
        .SYS_chown                      = &notImpl,
        .SYS_getcwd                     = &notImpl,
        .SYS_capget                     = &notImpl,
        .SYS_capset                     = &notImpl,
        .SYS_sigaltstack                = &notImpl,
        .SYS_sendfile                   = &notImpl,
        .SYS_getpmsg                    = &notImpl,
        .SYS_putpmsg                    = &notImpl,
        .SYS_vfork                      = &notImpl,
        .SYS_ugetrlimit                 = &notImpl,
        .SYS_mmap2                      = @ptrCast(&@import("mmap.zig").mmap2),
    });
};

pub const Syscall = enum(u10) {
    SYS_setup = 0,                  // 00
    SYS_exit,                       // 01
    SYS_fork,                       // 02
    SYS_read,                       // 03
    SYS_write,                      // 04
    SYS_open,                       // 05
    SYS_close,                      // 06
    SYS_waitpid,                    // 07
    SYS_creat,                      // 08
    SYS_link,                       // 09
    SYS_unlink,                     // 10
    SYS_execve,                     // 11
    SYS_chdir,                      // 12
    SYS_time,                       // 13
    SYS_mknod,                      // 14
    SYS_chmod,                      // 15
    SYS_lchown,                     // 16
    SYS_break,                      // 17
    SYS_oldstat,                    // 18
    SYS_lseek,                      // 19
    SYS_getpid,                     // 20
    SYS_mount,                      // 21
    SYS_umount,                     // 22
    SYS_setuid,                     // 23
    SYS_getuid,                     // 24
    SYS_stime,                      // 25
    SYS_ptrace,                     // 26
    SYS_alarm,                      // 27
    SYS_oldfstat,                   // 28
    SYS_pause,                      // 29
    SYS_utime,                      // 30
    SYS_stty,                       // 31
    SYS_gtty,                       // 32
    SYS_access,                     // 33
    SYS_nice,                       // 34
    SYS_ftime,                      // 35
    SYS_sync,                       // 36
    SYS_kill,                       // 37
    SYS_rename,                     // 38
    SYS_mkdir,                      // 39
    SYS_rmdir,                      // 40
    SYS_dup,                        // 41
    SYS_pipe,                       // 42
    SYS_times,                      // 43
    SYS_prof,                       // 44
    SYS_brk,                        // 45
    SYS_setgid,                     // 46
    SYS_getgid,                     // 47
    SYS_signal,                     // 48
    SYS_geteuid,                    // 49
    SYS_getegid,                    // 50
    SYS_acct,                       // 51
    SYS_umount2,                    // 52
    SYS_lock,                       // 53
    SYS_ioctl,                      // 54
    SYS_fcntl,                      // 55
    SYS_mpx,                        // 56
    SYS_setpgid,                    // 57
    SYS_ulimit,                     // 58
    SYS_oldolduname,                // 59
    SYS_umask,                      // 60
    SYS_chroot,                     // 61
    SYS_ustat,                      // 62
    SYS_dup2,                       // 63
    SYS_getppid,                    // 64
    SYS_getpgrp,                    // 65
    SYS_setsid,                     // 66
    SYS_sigaction,                  // 67
    SYS_sgetmask,                   // 68
    SYS_ssetmask,                   // 69
    SYS_setreuid,                   // 70
    SYS_setregid,                   // 71
    SYS_sigsuspend,                 // 72
    SYS_sigpending,                 // 73
    SYS_sethostname,                // 74
    SYS_setrlimit,                  // 75
    SYS_getrlimit,                  // 76
    SYS_getrusage,                  // 77
    SYS_gettimeofday,               // 78
    SYS_settimeofday,               // 79
    SYS_getgroups,                  // 80
    SYS_setgroups,                  // 81
    SYS_select,                     // 82
    SYS_symlink,                    // 83
    SYS_oldlstat,                   // 84
    SYS_readlink,                   // 85
    SYS_uselib,                     // 86
    SYS_swapon,                     // 87
    SYS_reboot,                     // 88
    SYS_readdir,                    // 89
    SYS_mmap,                       // 90
    SYS_munmap,                     // 91
    SYS_truncate,                   // 92
    SYS_ftruncate,                  // 93
    SYS_fchmod,                     // 94
    SYS_fchown,                     // 95
    SYS_getpriority,                // 96
    SYS_setpriority,                // 97
    SYS_profil,                     // 98
    SYS_statfs,                     // 99
    SYS_fstatfs,                    // 100
    SYS_ioperm,                     // 101
    SYS_socketcall,                 // 102
    SYS_syslog,                     // 103
    SYS_setitimer,                  // 104
    SYS_getitimer,                  // 105
    SYS_stat,                       // 106
    SYS_lstat,                      // 107
    SYS_fstat,                      // 108
    SYS_olduname,                   // 109
    SYS_iopl,                       // 110
    SYS_vhangup,                    // 111
    SYS_idle,                       // 112
    SYS_vm86old,                    // 113
    SYS_wait4,                      // 114
    SYS_swapoff,                    // 115
    SYS_sysinfo,                    // 116
    SYS_ipc,                        // 117
    SYS_fsync,                      // 118
    SYS_sigreturn,                  // 119
    SYS_clone,                      // 120
    SYS_setdomainname,              // 121
    SYS_uname,                      // 122
    SYS_modify_ldt,                 // 123
    SYS_adjtimex,                   // 124
    SYS_mprotect,                   // 125
    SYS_sigprocmask,                // 126
    SYS_create_module,              // 127
    SYS_init_module,                // 128
    SYS_delete_module,              // 129
    SYS_get_kernel_syms,            // 130
    SYS_quotactl,                   // 131
    SYS_getpgid,                    // 132
    SYS_fchdir,                     // 133
    SYS_bdflush,                    // 134
    SYS_sysfs,                      // 135
    SYS_personality,                // 136
    SYS_afs_syscall,                // 137
    SYS_setfsuid,                   // 138
    SYS_setfsgid,                   // 139
    SYS__llseek,                    // 140
    SYS_getdents,                   // 141
    SYS__newselect,                 // 142
    SYS_flock,                      // 143
    SYS_msync,                      // 144
    SYS_readv,                      // 145
    SYS_writev,                     // 146
    SYS_getsid,                     // 147
    SYS_fdatasync,                  // 148
    SYS__sysctl,                    // 149
    SYS_mlock,                      // 150
    SYS_munlock,                    // 151
    SYS_mlockall,                   // 152
    SYS_munlockall,                 // 153
    SYS_sched_setparam,             // 154
    SYS_sched_getparam,             // 155
    SYS_sched_setscheduler,         // 156
    SYS_sched_getscheduler,         // 157
    SYS_sched_yield,                // 158
    SYS_sched_get_priority_max,     // 159
    SYS_sched_get_priority_min,     // 160
    SYS_sched_rr_get_interval,      // 161
    SYS_nanosleep,                  // 162
    SYS_mremap,                     // 163
    SYS_setresuid,                  // 164
    SYS_getresuid,                  // 165
    SYS_vm86,                       // 166
    SYS_query_module,               // 167
    SYS_poll,                       // 168
    SYS_nfsservctl,                 // 169
    SYS_setresgid,                  // 170
    SYS_getresgid,                  // 171
    SYS_prctl,                      // 172
    SYS_rt_sigreturn,               // 173
    SYS_rt_sigaction,               // 174
    SYS_rt_sigprocmask,             // 175
    SYS_rt_sigpending,              // 176
    SYS_rt_sigtimedwait,            // 177
    SYS_rt_sigqueueinfo,            // 178
    SYS_rt_sigsuspend,              // 179
    SYS_pread,                      // 180
    SYS_pwrite,                     // 181
    SYS_chown,                      // 182
    SYS_getcwd,                     // 183
    SYS_capget,                     // 184
    SYS_capset,                     // 185
    SYS_sigaltstack,                // 186
    SYS_sendfile,                   // 187
    SYS_getpmsg,                    // 188
    SYS_putpmsg,                    // 189
    SYS_vfork,                      // 190
    SYS_ugetrlimit = 191,
    SYS_mmap2 = 192,
    _
};
