name: Deploy Docs on Main Merge

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        working-directory: ./docs
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        working-directory: ./docs
        run: pip install mkdocs-material pymdown-extensions  # Install both

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: docs/.cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy to GitHub Pages
        working-directory: ./docs
        run: mkdocs gh-deploy --force
